### PR TITLE
Create BaseCommandResponse trait

### PR DESCRIPTION
**Pull request by Kraagen**
@pcross616 @stotten @ladinu @malibuworkcrew @davis20 @mjwallin1 

Change Commands to return instances of a trait instead of a case class.

### CODE REVIEW

**Comment by malibuworkcrew** [comment]
So the only bummer about this is that it will break all our services that are currently using commands as they will need to change their execute methods and maybe even the content of said methods. So it was definitely necessary to change to this trait?

**Comment by malibuworkcrew** [comment]
Specifically common-collection and the whole sift stack, as it will even break services that are using the commands but not wookiee-spray

**Comment by Kraagen** [comment]
@malibuworkcrew The command logic uses the new BaseCommandResponse trait but individual commands can still use the CommandResponse since it now implements that trait. No required code changes was one of the major considerations in going this route.

Unfortunately, there will be the need to spin a new build of all the components that use discoverable commands since the class serialization version changes, but the code should be fully backward compatible.

**Comment by malibuworkcrew** [comment]
Aha, I see. Cool, well as long as everything using commands still works then in that case I am cool with this.

**Comment by malibuworkcrew** [comment]
@Kraagen I'm building new release, should be done in a couple minutes, it is 1.1.3, will likely have to bump in wookiee-spray

**Pull request merged**
