### PR TITLE
Using Zookeeper curator-x-discovery library to allow services/command…

### PR DESCRIPTION
**Pull request by Crashfreak**
…s to register themselves and make them discoverable by other services.

### CODE REVIEW

**Comment by Crashfreak** [comment]
@pcross616 @malibuworkcrew @mjwallin1 check this out

**Comment by pcross616** [comment]
Looks like  the pom is not correct and its failing something in the build.

**Comment by Crashfreak** [comment]
Ok fixed the POM, want to get this checked in so I can get a release pushed out.

**Comment by mjwallin1** [comment]
Looks good.

**Pull request merged**
